image: node:12-alpine

pipelines:
  branches:
    main:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm ci
            - npm run build
          artifacts:
            - public/**
      - step:
          name: Deploy
          deployment: production
          script:
            - npm install -g firebase-tools
            - firebase deploy --token "$FIREBASE_TOKEN"
