services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    restart: always
    user: 1000:1000
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    command: ["npm", "run", "docker-develop"]
