services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    restart: always
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - ${PORT:-8000}:8000
    volumes:
      - ./:/var/www
    command: ["npm", "run", "docker-develop"]
