version: '3.1'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    restart: always
    ports:
      - 8000:8000
    command: ["npm", "run", "develop"]
    user: 1000:1000
    volumes:
      - ./:/srv/app
